#! /bin/sh

case "$1" in
        start)
                echo "Init all network interfaces"
		ifup -a
                ;;
        stop)
		echo "Shutdown all network interfaces"        
		ifdown -a		
                ;;
        *)
                echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
