#! /bin/sh

case "$1" in
	start)
		echo "Starting OpenCV Server"
#		start-stop-daemon -S -x server -d /home/abbottjc/CU_Boulder/FINAL/opencv-monitoring-system/camera_app/cpp -- -d
		start-stop-daemon -S -x /usr/bin/opencv/camera_app/cpp/server -b
		;;
	stop)
        echo "Closing OpenCV Server"
#		start-stop-daemon -K -x server -d /home/abbottjc/CU_Boulder/FINAL/opencv-monitoring-system/camera_app/cpp
		start-stop-daemon -K -x /usr/bin/opencv/camera_app/cpp/server
                ;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac
exit 0
